/**
 * Local-development defaults.
 *
 * The deployed copy of this file is generated by .github/workflows/deploy.yml
 * from the PL_API_BASE and PL_SITE_URL repository variables — edits here only
 * affect running the console from a local checkout.
 */
window.PL_ADMIN_CONFIG = {
  apiBase: 'http://localhost:8080',
  siteUrl: 'http://localhost:4173',
};
